version: 2.1



jobs:
  build-and-deploy:
    parameters:
      repository:
        type: string
        default: "glbm-container" # Nombre del repositorio ECR por defecto
      image_tag:
        type: string
        default: "latest" # Tag de la imagen por defecto
      region:
        type: string
        default: "us-east-1" # Región de AWS por defecto

    docker:
      - image: circleci/python:3.9 
  
    steps:
      - setup_remote_docker:
            docker_layer_caching: true
      - checkout

      # Verificar instalación de Docker
      - run:
          name: Verificar instalación de Docker
          command: docker --version

      # Instalar AWS CLI
      - run:
          name: Instalar AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      # Configuración del AWS CLI con claves de entorno ya definidas en CircleCI
      - run:
          name: Configurar AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region << parameters.region >>
      
      # Verificar la identidad del usuario
      - run:
          name: Verificar la identidad del usuario
          command: |
            export AWS_PAGER=""
            aws sts get-caller-identity
      # Construcción de la imagen Docker
      - run:
          name: Construir la imagen Docker
          command: |
            docker build -t << parameters.repository >>:<< parameters.image_tag >> .

      # Autenticación con Amazon ECR
      - run:
          name: Autenticarse en Amazon ECR
          command: |
            aws ecr get-login-password --region << parameters.region >> | \
            docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.<< parameters.region >>.amazonaws.com

      # Etiquetar la imagen Docker
      - run:
          name: Etiquetar la imagen Docker
          command: |
            docker tag << parameters.repository >>:<< parameters.image_tag >> \
            abts17/simplenode:1.0.0
      - run:
          name: Test variables
          command: |
            echo $DOCKER_PASSWORD
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      # Subir la imagen a Amazon ECR
      - run:
          name: Subir la imagen Docker a ECR
          command: |
            docker push abts17/simplenode:1.0.0

  
workflows:
  version: 2
  deploy:
    jobs:
      - build-and-deploy:
          contexts:
            - DOCKER_SHARE
          # repository: "glbm-container"
          image_tag: "latest"
          filters:
            branches:
              only:
                - main
        